### ISSUE TITLE
NaNs produced during convergence when using covariate effects

### ISSUE THREAD

**Issue by stulacy** [jrdnmdhl/flexsurvcure#9]
I've tried a number of different mixture cure models using the Weibull to model survival and whenever I add covariate effects I get a warning that NaNs were produced. I also occasionally get the non-positive determinant of the Hessian. I've tried this on a simulated data set and a real one and the same errors still occur.

**Comment by jrdnmdhl** [comment]
Getting a few NaNs when fitting a Weibull is OK and not symptomatic of any problems with the fit.  The same thing happens with Weibulls in flexsurv, though these warnings are suppressed.

For your issues with convergence, I would suggest looking at page 10 of the flexsurv manual.  The same suggestions would apply here as well: https://cran.r-project.org/web/packages/flexsurv/flexsurv.pdf
